import "./globals.css";

import { FontContextProvider } from "@/contexts/FontContextProvider";
import { ThemeContextProvider } from "@/contexts/ThemeContextProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeContextProvider>
          <FontContextProvider>{children}</FontContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
